### ISSUE TITLE
Raising this issue in the WHATWG

### ISSUE THREAD

**Issue by foolip** [filamentgroup/html-video-responsive#3]
I came across this [on Twitter](https://twitter.com/scottjehl/status/1349710278481637377) and since I've been involved I wanted to provide more background and make a suggestion.

This was removed from the spec in https://www.w3.org/Bugs/Public/show_bug.cgi?id=19619, and the discussion there is worth looking over. It mostly boils down to the observations listed in https://github.com/filamentgroup/html-video-responsive#challenges-and-differences-from-picture. I was initially [skeptical](https://www.w3.org/Bugs/Public/show_bug.cgi?id=19619#c1) of removal, but eventually came around to [removing it from Blink](https://groups.google.com/a/chromium.org/g/blink-dev/c/5sWUMC_d8Tg/m/ZZ0Z7rfeCqUJ), which then led to the spec removal. I was happy about that outcome at the time, but seeing repo/proposal I'm not so sure it was the right call.

It would be great if you could file an issue at https://github.com/whatwg/html/issues/new about solving the problem of video delivery size on mobile. It's very interesting to see that it's actually heavier on mobile than on desktop, and it seems like an important problem to solve. Whether reviving the `media` attribute is the way to make it happen I'm not sure, but it seems well worth revisiting, 6 years later.

cc @zcorpan

**Comment by kentcdodds** [comment]
For anyone who lands here, I found what appears to be the relevant issue: https://github.com/whatwg/html/issues/6363
